version: 2
jobs:

  search:
    working_directory: ~/build
    docker:
      - image: node:8.10.0
    steps:
      - attach_workspace:
          at: ~/build
      - checkout
      - run: mkdir static
      - run:
          name: install node dependencies
          command: npm install 
      - run:
          name: build indexes
          command:  node ./.build_scripts/build_index.js
      - run:
          name: show static contents
          command: ls static
      - persist_to_workspace:
          root: .
          paths: static

  build:
    working_directory: ~/build
    docker:
      - image: cibuilds/hugo:latest

    steps:
      - checkout
      - attach_workspace:
          at: ~/build
      - run: git submodule sync && git submodule update --init
      - run: HUGO_ENV=production hugo
      - run:
          name: list public
          command: ls public
      - persist_to_workspace:
          root: .
          paths: public

  clean:
    working_directory: ~/build
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/build
      - run:
          name: install python dependencies
          command: sudo pip install python-frontmatter && sudo pip install toml
      - run:
          name: make output directory
          command: mkdir pdf-build
      - run: 
          name: clean combine and copy markdown into pdf-build
          command: python .build_scripts/clean.py
      - run: 
          name: list files in public
          command: ls public
      - persist_to_workspace:
          root: .
          paths: [public, pdf-build]
  pdf:
    working_directory: ~/build
    docker:
      - image: dalibo/pandocker
    steps:
      - checkout
      - attach_workspace:
          at: ~/build
      - run:
          wget https://fonts.google.com/download?family=Archivo -O ~/archivo.zip && unzip ~/archivo.zip -d ~/.fonts
      - run: >
          mkdir ~/build/public/pdfs &&
          cd pdf-build &&
          for d in $(find * -type d); do
              mkdir ~/build/public/pdfs/"$d"
          done &&
          for i in $(find *); do
              if [ -f "$i" ] && [ ${i: -3} == ".md" ]; then
                  pandoc $i -o ~/build/public/pdfs/${i//\.md/.pdf} --pdf-engine=xelatex -V geometry:margin=1in -V papersize:a4 -V mainfont:Archivo-Regular
              fi
          done
      - run: 
          name: list files in public
          command: ls public
      - persist_to_workspace:
          root: .
          paths: public


  deploy:
    working_directory: ~/build
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/build
      - run: touch .nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ciricleci_build@hotosm.org"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "b4:94:b8:6b:f4:0b:b5:0e:40:ba:1c:f7:b8:d9:d4:4c"
      - run: 
          name: list files pushed
          command: ls public
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist public

workflows:
  version: 2

  build_and_pdf:
    jobs:
      - search:
          filters:
            branches:
              only: master
      - build:
          requires:
            - search
          filters:
            branches:
              only: master
      - clean:
          requires:
            - build
          filters:
            branches:
              only: master
      - pdf:
          requires:
            - clean
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - pdf
          filters:
            branches:
              only: master