languageCode = "en-us"
title = "UAV Mapping Guidelines"
theme = "hotdocs"
DefaultContentLanguage = "en"
relativeurls = true
enableGitInfo = true

[params]
    DefaultContentLanguage = "en"
    GithubRepo = "https://github.com/hotosm/uav-mapping-guidelines"
    SiteURL = "https://uav-guidelines.openaerialmap.org"

[imaging]
    resampleFilter = "box"
    quality = 75